server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/**
          filters:
        #            - RewritePath=/reservation/(?<segment>.*),/$\{segment}
        - id: showtime-and-theatre-service
          uri: lb://SHOWTIME-AND-THEATRE-SERVICE
          predicates:
            - Path=/showtime-and-theatre/**
          filters:
        #            - RewritePath=/showtime-and-theatre/(?<segment>.*),/$\{segment}
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
          filters:
        #            - RewritePath=/movie/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
        #            - RewritePath=/user/(?<segment>.*),/$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**


jwt:
  secret: thisIsASecret